spring.application.name=task-management-app

# DB config
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/task_management
spring.datasource.username = postgres
spring.datasource.password = 123

# JPA configuration
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# View resolver
spring.mvc.view.prefix = /WEB-INF/views/
spring.mvc.view.suffix = .jsp